name: build

on:
  push:
    branches:
      - 'main'
      - 'vrumger'
      - 'rr/**' # "rr" stands for "remote run"
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-release:
    strategy:
      # fail-fast: false # Disable fail-fast in matrix
      matrix:
        os: [macos-26]
    name: build-release
    runs-on: ${{ matrix.os }}
    steps:
      - run: env # Debug
      - uses: actions/checkout@v3
      - run: ./.github/gh-actions-runner-xcode-select.sh
      - run: brew install bash fish xcbeautify swiftly
      - run: swiftly init --skip-install --assume-yes --verbose && swiftly install
      - name: './build-release.sh'
        run: |
          # "-" means "Sign to run locally". There is no aerospace-codesign-certificate on GH Actions
          ./build-release.sh --codesign-identity -
          ./install-from-sources.sh --dont-rebuild
      - name: cat ./.release/xcodebuild.log
        if: ${{ always() }}
        run: 'if test -f ./.release/xcodebuild.log; then cat ./.release/xcodebuild.log; fi'
      - name: 'tar files'
        run: tar -cvf apps.tar /Applications/AeroSpace.app /opt/homebrew/Caskroom/aerospace-dev/latest/AeroSpace-v0.0.0-SNAPSHOT/bin
      - name: upload build artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: apps.tar
