name: Build

on:
  push:
    branches:
      - 'main'
      - 'bobko/**'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # every day at 00:00

jobs:
  build:
    strategy:
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md
        os: [macos-13, macos-14]
    name: Build
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            swift-exec-deps/.build
            .deps
          key: ${{ matrix.os }}-${{ runner.arch }}-${{ hashFiles('script/install-deps.sh', 'swift-exec-deps/Package.swift', 'swift-exec-deps/Package.resolved', 'Gemfile', '.bundle/config') }}
      - run: brew install bash fish xcbeautify
      - run: ./script/install-deps.sh
      # "-" means "Sign to run locally". There is no aerospace-codesign-certificate in GH Actions
      - run: ./build-debug.sh
      - run: ./run-tests.sh
      - run: ./build-release.sh --codesign-identity -
      - uses: actions/upload-artifact@v4
        with:
          path: .release