name: sync with upstream

on:
  schedule:
    - cron: '0 0 * * 0' # every sunday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: sync with upstream

    steps:
      - uses: actions/checkout@v5
      - uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: ${{ github.ref_name }}
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: nikitabobko/AeroSpace
